using UnityEngine;

namespace Elementborn.Game
{
    /// <summary>
    /// Convenience component for UI prefabs generated by the v25 setup tools.
    /// It tries to find important gameplay objects at runtime and wire panel references.
    /// </summary>
    public sealed class HudPanelAutoBinder : MonoBehaviour
    {
        [SerializeField] private bool bindOnStart = true;
        [SerializeField] private bool includeInactive = true;

        private void Start()
        {
            if (bindOnStart)
            {
                Bind();
            }
        }

        [ContextMenu("Bind HUD Panels")]
        public void Bind()
        {
            Transform player = GameObject.FindGameObjectWithTag("Player") != null
                ? GameObject.FindGameObjectWithTag("Player").transform
                : null;

            foreach (var questHud in GetComponentsInChildren<QuestTrackerHudView>(includeInactive))
            {
                SetPrivateField(questHud, "player", player);
            }

            SpellCastController spellCastController = player != null ? player.GetComponent<SpellCastController>() : ElementbornFindUtility.FindFirst<SpellCastController>();
            SpellResourcePool spellResourcePool = player != null ? player.GetComponent<SpellResourcePool>() : ElementbornFindUtility.FindFirst<SpellResourcePool>();
            SpellLoadoutController spellLoadout = player != null ? player.GetComponent<SpellLoadoutController>() : ElementbornFindUtility.FindFirst<SpellLoadoutController>();
            CombatDefenseController defense = player != null ? player.GetComponent<CombatDefenseController>() : ElementbornFindUtility.FindFirst<CombatDefenseController>();

            foreach (var castBar in GetComponentsInChildren<SpellCastBarView>(includeInactive))
            {
                SetPrivateField(castBar, "caster", spellCastController);
            }

            foreach (var resourceBar in GetComponentsInChildren<SpellResourceBarView>(includeInactive))
            {
                SetPrivateField(resourceBar, "resourcePool", spellResourcePool);
            }

            foreach (var loadoutView in GetComponentsInChildren<SpellLoadoutHudView>(includeInactive))
            {
                SetPrivateField(loadoutView, "loadout", spellLoadout);
            }

            foreach (var defensePanel in GetComponentsInChildren<CombatDefenseDebugPanel>(includeInactive))
            {
                SetPrivateField(defensePanel, "defense", defense);
            }
        }

        private void SetPrivateField(object target, string fieldName, object value)
        {
            if (target == null)
            {
                return;
            }

            var field = target.GetType().GetField(fieldName, System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
            if (field != null)
            {
                field.SetValue(target, value);
            }
        }
    }
}
