#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Elementborn.Game.EditorTools
{
    public static class ElementbornUiPrefabReportMenu
    {
        [MenuItem("Elementborn/UI Prefabs/Write UI Prefab Report")]
        public static void WriteReport()
        {
            string dir = "Assets/Elementborn/Generated/Reports";
            Directory.CreateDirectory(dir);
            string path = $"{dir}/UiPrefabReport.md";
            File.WriteAllText(path,
@"# Elementborn UI Prefab Report

Generated by v25.

## Prefabs

```text
Assets/Elementborn/Generated/Prefabs/UI/Elementborn_PlayableHudCanvas.prefab
Assets/Elementborn/Generated/Prefabs/UI/Elementborn_QuestLogCanvas.prefab
Assets/Elementborn/Generated/Prefabs/UI/Elementborn_BossHudCanvas.prefab
Assets/Elementborn/Generated/Prefabs/UI/Elementborn_SpellHudCanvas.prefab
Assets/Elementborn/Generated/Prefabs/UI/Elementborn_DebugHudCanvas.prefab
```

## Theme

```text
Assets/Elementborn/Generated/UI/Elementborn_DefaultUiTheme.asset
```

## Menu items

```text
Elementborn → UI Prefabs → Create All Polished UI Prefabs
Elementborn → UI Prefabs → Install Playable HUD In Open Scene
Elementborn → UI Prefabs → Install Boss HUD In Open Scene
Elementborn → UI Prefabs → Install Spell HUD In Open Scene
Elementborn → UI Prefabs → Write UI Prefab Report
```

## Controls

```text
J  → toggle quest log
F9 → toggle debug panel
1-4 → cast spell loadout slots
Right Mouse Button → block
Left Alt → dodge
```

## Notes

The prefabs use legacy UnityEngine.UI components so they work in the current scaffold without requiring UI Toolkit setup.
");
            AssetDatabase.Refresh();
            Debug.Log($"Wrote {path}");
        }
    }
}
#endif
