#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using Elementborn.Game;

namespace Elementborn.Game.EditorTools
{
    public static class NarrativeRuntimeSaveSetupMenu
    {
        private const string PrefabDir = "Assets/Elementborn/Generated/Prefabs/Save";
        private const string ReportDir = "Assets/Elementborn/Generated/Reports";

        [MenuItem("Elementborn/Save/Install Narrative Runtime Save Bridges")]
        public static void InstallNarrativeRuntimeSaveBridges()
        {
            Directory.CreateDirectory(PrefabDir);
            Directory.CreateDirectory(ReportDir);

            GameObject root = GameObject.Find("Elementborn Narrative Runtime Save");
            if (root == null)
            {
                root = new GameObject("Elementborn Narrative Runtime Save");
            }

            if (root.GetComponent<NarrativeRuntimeSaveBridge>() == null)
            {
                root.AddComponent<NarrativeRuntimeSaveBridge>();
            }

            if (root.GetComponent<CapitalWorldStateSaveBridge>() == null)
            {
                root.AddComponent<CapitalWorldStateSaveBridge>();
            }

            if (root.GetComponent<PoliticalWorldEventDirectorSaveBridge>() == null)
            {
                root.AddComponent<PoliticalWorldEventDirectorSaveBridge>();
            }

            if (root.GetComponent<QuestChainSaveBridge>() == null)
            {
                root.AddComponent<QuestChainSaveBridge>();
            }

            if (root.GetComponent<CreatureOrphanageRecoverySaveBridge>() == null)
            {
                root.AddComponent<CreatureOrphanageRecoverySaveBridge>();
            }

            if (root.GetComponent<NarrativeRuntimeSaveAdminCommandBridge>() == null)
            {
                root.AddComponent<NarrativeRuntimeSaveAdminCommandBridge>();
            }

            PrefabUtility.SaveAsPrefabAsset(root, $"{PrefabDir}/Elementborn_NarrativeRuntimeSave.prefab");
            File.WriteAllText($"{ReportDir}/NarrativeRuntimeSaveReport.md",
@"# Narrative Runtime Save Report

Generated by v37.

## Saved systems

```text
CapitalWorldStateTracker
PoliticalWorldEventDirector
QuestChainDirector
```

## Runtime command bridge

```text
narrative.save
narrative.load
narrative.save slot
narrative.load slot
narrative.delete slot
```

## Save file folders

```text
Application.persistentDataPath/capital_world_state
Application.persistentDataPath/political_world_events
Application.persistentDataPath/quest_chains
```
");

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("Installed narrative runtime save bridges.");
        }
    }
}
#endif
