#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using Elementborn.Game;

namespace Elementborn.Game.EditorTools
{
    public static class NpcAdminEditorTools
    {
        private const string PrefabDir = "Assets/Elementborn/Generated/Prefabs/NPC";
        private const string ReportDir = "Assets/Elementborn/Generated/Reports";
        private const string ManifestPath = "Assets/Elementborn/Generated/NPC/Integration/NpcWorldIntegrationManifest.asset";

        [MenuItem("Elementborn/NPC Tools/Create NPC Admin UI Prefab")]
        public static void CreateNpcAdminUiPrefab()
        {
            Directory.CreateDirectory(PrefabDir);
            GameObject canvas = new GameObject("Elementborn_NpcAdminCanvas");
            var c = canvas.AddComponent<Canvas>();
            c.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.AddComponent<CanvasScaler>();
            canvas.AddComponent<GraphicRaycaster>();

            GameObject panel = CreatePanel(canvas.transform, "NPC Admin Panel", new Vector2(0, 0), new Vector2(760, 560));
            var view = panel.AddComponent<NpcAdminPanelView>();

            Text title = CreateText(panel.transform, "Title", "NPC Admin", 30, new Vector2(0, -28), new Vector2(700, 40));
            InputField search = CreateInput(panel.transform, "Search Input", "Search name, origin, notes...", new Vector2(0, -85), new Vector2(660, 38));
            InputField region = CreateInput(panel.transform, "Region Input", "Region filter...", new Vector2(-170, -135), new Vector2(320, 34));
            InputField element = CreateInput(panel.transform, "Element Input", "Element filter...", new Vector2(170, -135), new Vector2(320, 34));
            Text results = CreateText(panel.transform, "Results Text", "Run refresh to list NPCs.", 16, new Vector2(0, -330), new Vector2(680, 330));
            results.alignment = TextAnchor.UpperLeft;

            SetPrivate(view, "searchInput", search);
            SetPrivate(view, "regionInput", region);
            SetPrivate(view, "elementInput", element);
            SetPrivate(view, "resultsText", results);

            PrefabUtility.SaveAsPrefabAsset(canvas, $"{PrefabDir}/Elementborn_NpcAdminCanvas.prefab");
            Object.DestroyImmediate(canvas);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("Created NPC Admin UI prefab.");
        }

        [MenuItem("Elementborn/NPC Tools/Install NPC Admin Tools In Open Scene")]
        public static void InstallNpcAdminTools()
        {
            NpcWorldIntegrationAssetGenerator.GenerateAll();
            CreateNpcAdminUiPrefab();

            GameObject tools = GameObject.Find("Elementborn NPC Admin Tools");
            if (tools == null)
            {
                tools = new GameObject("Elementborn NPC Admin Tools");
            }

            var registry = tools.GetComponent<NpcAdminRegistry>();
            if (registry == null)
            {
                registry = tools.AddComponent<NpcAdminRegistry>();
            }

            var manifest = AssetDatabase.LoadAssetAtPath<NpcWorldIntegrationManifest>(ManifestPath);
            registry.SetManifest(manifest);

            if (tools.GetComponent<NpcAdminCommandBridge>() == null)
            {
                tools.AddComponent<NpcAdminCommandBridge>();
            }

            if (tools.GetComponent<NpcPlacementAdminTool>() == null)
            {
                tools.AddComponent<NpcPlacementAdminTool>();
            }

            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>($"{PrefabDir}/Elementborn_NpcAdminCanvas.prefab");
            if (prefab != null && GameObject.Find("Elementborn_NpcAdminCanvas") == null)
            {
                PrefabUtility.InstantiatePrefab(prefab);
            }

            EditorUtility.SetDirty(tools);
            Debug.Log("Installed NPC Admin Tools in open scene.");
        }

        [MenuItem("Elementborn/NPC Tools/Write NPC Admin Report")]
        public static void WriteNpcAdminReport()
        {
            NpcWorldIntegrationAssetGenerator.GenerateAll();
            Directory.CreateDirectory(ReportDir);
            string path = $"{ReportDir}/NpcAdminReport.md";
            File.WriteAllText(path,
@"# NPC Admin Report

Generated by v30.

## Menu items

```text
Elementborn → NPC Tools → Create NPC Admin UI Prefab
Elementborn → NPC Tools → Install NPC Admin Tools In Open Scene
Elementborn → NPC Tools → Write NPC Admin Report
```

## Runtime commands

```text
npc.list
npc.search text
npc.region regionName
npc.element elementName
npc.id npcId
npc.place npcId
```

## New rosters

```text
Assets/Elementborn/Generated/NPC/Rosters/neritha_pirate_crew.csv
Assets/Elementborn/Generated/NPC/Rosters/social_circle_and_neighbors.csv
```

Includes:

```text
Captain Ramón
First Mate Sarah
Rekr Ap
Manon
Marie Conflag
Amy Whine
Kelly
Johna Rold
```

## Notes

Captain Ramón and First Mate Sarah are tied to the Raucous Tide, a pirate ship known for lavish celebratory parties after raids and fights.

The social-circle roster adds a Wind Capital neighborhood cluster plus Kelly in the Fire Capital for lighter domestic hooks, advice scenes, and small-scale local quests.
");
            AssetDatabase.Refresh();
            Debug.Log($"Wrote {path}");
        }

        private static GameObject CreatePanel(Transform parent, string name, Vector2 position, Vector2 size)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);
            RectTransform rect = go.AddComponent<RectTransform>();
            rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = position;
            rect.sizeDelta = size;
            Image image = go.AddComponent<Image>();
            image.color = new Color(0.06f, 0.16f, 0.26f, 0.94f);
            return go;
        }

        private static Text CreateText(Transform parent, string name, string text, int size, Vector2 position, Vector2 rectSize)
        {
            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);
            RectTransform rect = go.AddComponent<RectTransform>();
            rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = position;
            rect.sizeDelta = rectSize;
            Text label = go.AddComponent<Text>();
            label.text = text;
            Elementborn.Game.ElementbornBuiltinFontUtility.ApplyDefaultFont(label);
            label.fontSize = size;
            label.alignment = TextAnchor.MiddleCenter;
            label.color = new Color(1f, 0.96f, 0.86f, 1f);
            label.horizontalOverflow = HorizontalWrapMode.Wrap;
            label.verticalOverflow = VerticalWrapMode.Overflow;
            return label;
        }

        private static InputField CreateInput(Transform parent, string name, string placeholder, Vector2 position, Vector2 rectSize)
        {
            GameObject root = new GameObject(name);
            root.transform.SetParent(parent, false);
            RectTransform rect = root.AddComponent<RectTransform>();
            rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = position;
            rect.sizeDelta = rectSize;
            Image image = root.AddComponent<Image>();
            image.color = new Color(1f, 1f, 1f, 0.18f);
            InputField input = root.AddComponent<InputField>();

            Text text = CreateText(root.transform, "Text", "", 16, Vector2.zero, rectSize - new Vector2(16, 8));
            text.alignment = TextAnchor.MiddleLeft;
            Text placeholderText = CreateText(root.transform, "Placeholder", placeholder, 16, Vector2.zero, rectSize - new Vector2(16, 8));
            placeholderText.alignment = TextAnchor.MiddleLeft;
            placeholderText.color = new Color(1f, 1f, 1f, 0.45f);

            input.textComponent = text;
            input.placeholder = placeholderText;
            return input;
        }

        private static void SetPrivate(object target, string fieldName, object value)
        {
            var field = target.GetType().GetField(fieldName, System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
            if (field != null)
            {
                field.SetValue(target, value);
                EditorUtility.SetDirty(target as Object);
            }
        }
    }
}
#endif
