#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using Elementborn.Game;

namespace Elementborn.Game.EditorTools
{
    public static class SocialNpcRosterGenerator
    {
        private const string RosterPath = "Assets/Elementborn/Generated/NPC/Rosters/social_circle_and_neighbors.csv";
        private const string ReportPath = "Assets/Elementborn/Generated/Reports/SocialCircleNpcReport.md";

        [MenuItem("Elementborn/NPC Tools/Generate Social Circle NPC Roster")]
        public static void GenerateRoster()
        {
            if (!File.Exists(RosterPath))
            {
                Debug.LogWarning("Expected social circle roster CSV was not found. Importing all existing rosters instead.");
            }

            NpcRosterCsvImporter.ImportAllRosters();
            WriteReportInternal();
            AssetDatabase.Refresh();
            Debug.Log("Generated/imported the social circle NPC roster.");
        }

        [MenuItem("Elementborn/NPC Tools/Write Social Circle NPC Report")]
        public static void WriteReport()
        {
            WriteReportInternal();
            AssetDatabase.Refresh();
            Debug.Log("Wrote social circle NPC report.");
        }

        private static void WriteReportInternal()
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ReportPath));
            File.WriteAllText(ReportPath,
@"# Social Circle NPC Report

Generated by v41.

## Roster CSV

```text
Assets/Elementborn/Generated/NPC/Rosters/social_circle_and_neighbors.csv
```

## Included NPCs

```text
Rekr Ap
Manon
Marie Conflag
Amy Whine
Kelly
Johna Rold
```

## Notes

- Rekr, Manon, Marie, and Amy form a social cluster in the Wind Capital lower terraces.
- Kelly is a protective lava-channeler contact for Fire Capital neighborhood content.
- Johna Rold works well as a rumor source, advice NPC, or low-pressure quest giver.
- Marie creates comic fire hazards; Johna reduces social tension; Kelly can anchor protective local quests.
");
        }
    }
}
#endif
