#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using Elementborn.Game;

namespace Elementborn.Game.EditorTools
{
    public static class StoryEncounterQuestAssetGenerator
    {
        private const string QuestDir = "Assets/Elementborn/Generated/QuestUI/StoryEncounters";
        private const string ReportDir = "Assets/Elementborn/Generated/Reports";

        [MenuItem("Elementborn/Story Encounters/Generate Encounter Quests")]
        public static void GenerateAll()
        {
            Directory.CreateDirectory(QuestDir);
            Directory.CreateDirectory(ReportDir);
            StoryEncounterAssetGenerator.GenerateAll();

            CreateQuest("donowl_drowsy_menace", "Donowl, the Drowsy Menace", "Donowl is very strong, slightly confused, and keeps falling asleep mid-threat.", "Donowl", new[]
            {
                ("find_donowl", "Find Donowl in the Drowsy Ruins", "Locate the sleepy owl monster.", new Vector3(18f, 0f, 44f)),
                ("distract_donowl", "Distract Donowl", "Use something shiny, loud, or snack-shaped to pull Donowl away.", new Vector3(20f, 0f, 46f)),
                ("resolve_donowl", "Resolve the sleepy threat", "Defeat, redirect, or outwit Donowl.", new Vector3(18f, 0f, 44f))
            });

            CreateQuest("judge_thunder_verdict", "The Judge's Thunder Verdict", "The neon pink steam dragon protects her territory and judges trespassers harshly.", "The Judge", new[]
            {
                ("approach_perch", "Approach the Steam-Bright Perch", "Enter the edge of The Judge's protected area.", new Vector3(490f, 20f, 260f)),
                ("survive_warning", "Survive the thunder-cracked warning", "Her voice breaks like a storm over the ground.", new Vector3(492f, 20f, 262f)),
                ("earn_or_defy_verdict", "Earn or defy the verdict", "Convince The Judge, retreat, or fight through her judgment.", new Vector3(490f, 20f, 260f))
            });

            CreateQuest("romilus_madrangea_pack_hunt", "The Five-Minute Pack Hunt", "The wolf pack respawns unless Romilus and Madrangea are both defeated within five minutes.", "Romilus and Madrangea", new[]
            {
                ("track_pack", "Track the wolf pack patrol", "Find the patrol route and identify both leaders.", new Vector3(-260f, 0f, 310f)),
                ("defeat_romilus", "Defeat Romilus", "Bring down the alpha.", new Vector3(-260f, 0f, 310f)),
                ("defeat_madrangea", "Defeat Madrangea within five minutes", "Defeat the matriarch before the pack regroups.", new Vector3(-264f, 0f, 314f))
            });

            CreateQuest("michelle_rules_of_blood", "Michelle Raindancer's Rules of Blood", "Michelle believes rules matter more than mercy and destroys anyone who breaks them.", "Michelle Raindancer", new[]
            {
                ("hear_law", "Hear Michelle's law", "Learn what rule has supposedly been broken.", new Vector3(730f, 25f, 418f)),
                ("find_exception", "Find the exception", "Search for proof that mercy matters more than rigid law.", new Vector3(728f, 25f, 416f)),
                ("face_michelle", "Face Michelle's judgment", "Confront the blood-channeler vizier.", new Vector3(730f, 25f, 418f))
            });

            CreateQuest("crab_sign_orphanage_help", "The Crab-Sign Orphanage", "Ella and Eloc heal creatures and somehow turn every crisis into a loving argument about crabs.", "Ella and Eloc", new[]
            {
                ("visit_orphanage", "Visit the crab-sign orphanage", "Meet Ella and Eloc.", new Vector3(210f, 0f, 284f)),
                ("bring_creature", "Bring a creature that needs help", "Lead or carry a creature to the orphanage.", new Vector3(212f, 0f, 285f)),
                ("heal_creature", "Let Ella and Eloc heal the creature", "Let the orphanage work its environmental magic.", new Vector3(214f, 0f, 286f))
            });

            File.WriteAllText($"{ReportDir}/StoryEncounterQuestReport.md", "# Story Encounter Quest Report\n\nGenerated by v39.\n\n- Donowl, the Drowsy Menace\n- The Judge's Thunder Verdict\n- The Five-Minute Pack Hunt\n- Michelle Raindancer's Rules of Blood\n- The Crab-Sign Orphanage\n");
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("Generated story encounter quests.");
        }

        private static QuestUiDefinition CreateQuest(string id, string title, string description, string giver, (string id, string title, string description, Vector3 position)[] objectives)
        {
            string path = $"{QuestDir}/{id}.asset";
            var quest = AssetDatabase.LoadAssetAtPath<QuestUiDefinition>(path);
            if (quest == null)
            {
                quest = ScriptableObject.CreateInstance<QuestUiDefinition>();
                AssetDatabase.CreateAsset(quest, path);
            }

            var so = new SerializedObject(quest);
            so.FindProperty("questId").stringValue = id;
            so.FindProperty("title").stringValue = title;
            so.FindProperty("description").stringValue = description;
            so.FindProperty("region").stringValue = "Story Encounters";
            so.FindProperty("giverName").stringValue = giver;
            so.FindProperty("autoTrack").boolValue = true;

            var objectiveArray = so.FindProperty("objectives");
            objectiveArray.arraySize = objectives.Length;
            for (int i = 0; i < objectives.Length; i++)
            {
                var objective = objectiveArray.GetArrayElementAtIndex(i);
                objective.FindPropertyRelative("ObjectiveId").stringValue = objectives[i].id;
                objective.FindPropertyRelative("Title").stringValue = objectives[i].title;
                objective.FindPropertyRelative("Description").stringValue = objectives[i].description;
                objective.FindPropertyRelative("WorldPosition").vector3Value = objectives[i].position;
                objective.FindPropertyRelative("CreateWaypoint").boolValue = true;
                objective.FindPropertyRelative("Required").boolValue = true;
            }

            var rewards = so.FindProperty("rewards");
            rewards.arraySize = 1;
            var reward = rewards.GetArrayElementAtIndex(0);
            reward.FindPropertyRelative("RewardId").stringValue = id + "_reward";
            reward.FindPropertyRelative("DisplayName").stringValue = "Story Encounter Progress";
            reward.FindPropertyRelative("Currency").intValue = 25;
            reward.FindPropertyRelative("SkillPoints").intValue = 0;

            so.ApplyModifiedProperties();
            EditorUtility.SetDirty(quest);
            return quest;
        }
    }
}
#endif
