#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using Elementborn.Game;

namespace Elementborn.Game.EditorTools
{
    public static class UnityRuntimeSafetySetupMenu
    {
        private const string ReportDir = "Assets/Elementborn/Generated/Reports";

        [MenuItem("Elementborn/Unity Setup/Add Runtime Safety Net To Open Scene")]
        public static void AddRuntimeSafetyNet()
        {
            GameObject existing = GameObject.Find("Elementborn Runtime Safety Net");
            if (existing == null)
            {
                existing = new GameObject("Elementborn Runtime Safety Net");
            }

            existing.EnsureComponent<RuntimeSceneSafetyNet>();
            existing.EnsureComponent<RuntimeNullReferenceGuard>();
            existing.EnsureComponent<GeneratedContentPresenceReport>();
            EditorUtility.SetDirty(existing);
            Debug.Log("Added RuntimeSceneSafetyNet, RuntimeNullReferenceGuard, and GeneratedContentPresenceReport to open scene.");
        }

        [MenuItem("Elementborn/Unity Setup/Write Runtime Safety Report")]
        public static void WriteRuntimeSafetyReport()
        {
            Directory.CreateDirectory(ReportDir);
            string path = $"{ReportDir}/RuntimeSafetyReport.md";
            File.WriteAllText(path,
@"# Runtime Safety Report

This report is generated by v24.

## Added safety helpers

- ElementbornFindUtility
- SafeComponentExtensions
- RuntimeSceneSafetyNet
- RuntimeNullReferenceGuard
- GeneratedContentPresenceReport

## Recommended scene object

Add this to any play-test scene:

```text
Elementborn Runtime Safety Net
```

with:

```text
RuntimeSceneSafetyNet
RuntimeNullReferenceGuard
GeneratedContentPresenceReport
```

## Recommended Unity menu order

```text
1. Elementborn → Unity Setup → Run Recommended Project Setup
2. Elementborn → Unity Setup → Add Runtime Safety Net To Open Scene
3. Elementborn → Starter Content → Run All Starter Generators Safely
4. Elementborn → Playable Setup → Build Full Test Scene
5. Elementborn → Unity Setup → Add Playable Test Scene To Build Settings
```

## Notes

RuntimeSceneSafetyNet can create fallback objects for:

- EventSystem
- Main Camera
- UI Canvas
- Runtime Bootstrap
- Player capsule with core test components
");
            AssetDatabase.Refresh();
            Debug.Log($"Wrote {path}");
        }
    }
}
#endif
